void print_alphabet(void);
int _putchar(char c);
void _puts_recursion(char *s);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int n);
int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void print_triangle(int size);
void reset_to_98(int n);
void swap_int(inta, int b);
int _strlen(chars);
void _puts(char str);
void print_rev(chars);
void rev_string(char s);
void puts2(charstr);
void puts_half(char str);
void print_array(inta, int n);
char _strcpy(chardest, char src);
int _atoi(chars);
char _strcat(chardest, char src);
char_strncat(char dest, charsrc, int n);
char _strncpy(chardest, char src, int n);
int _strcmp(chars1, char s2);
void reverse_array(inta, int n);
char string_toupper(char);
char cap_string(char);
char _memset(chars, char b, unsigned int n);
char _memcpy(chardest, char src, unsigned int n);
char_strchr(char s, char c);
unsigned int _strspn(chars, char accept);
char_strpbrk(char s, characcept);
char _strstr(charhaystack, char needle);
void print_chessboard(char (a)[8]);
void print_diagsums(int a, int size);
void _puts_recursion(chars);
